---
- name: VMware vCenter 
  hosts: all
  gather_facts: no
  
  tasks:
  - name:  Get VM UUIDs
    community.vmware.vmware_guset_info:
      validate_certs: no
      name: "{{ inventory_hostname }}"
    delegate_to: localhost
    register: vm_info
    ignore_errors: yes
